In [17]:
#   Pessoas cadastradas no Cadastro Único - por sexo  

import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
#magia maluca que faz from utils import helper funcionar ^
import pandas as pd
import helper

df = pd.read_csv('dados_brutos/sexo_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
'Número de pessoas do sexo masculino cadastradas no Cadastro Único':'Homens',
'Número de pessoas do sexo feminino cadastradas no Cadastro Único':'Mulheres'},inplace=True)


df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)


df.drop(columns=['UF'],inplace=True)

df

       Codigo   Municipio  Homens  Mulheres   Ano         RI
10     150010  ABAETETUBA   58440     70994  2025  Tocantins
28     150010  ABAETETUBA   59279     70507  2024  Tocantins
40     150010  ABAETETUBA   64150     72134  2023  Tocantins
50     150010  ABAETETUBA   62504     70334  2022  Tocantins
58     150010  ABAETETUBA   53959     65039  2021  Tocantins
...       ...         ...     ...       ...   ...        ...
24127  150840    XINGUARA    9724     12242  2016   Araguaia
24141  150840    XINGUARA    9340     11671  2015   Araguaia
24151  150840    XINGUARA   10522     12996  2014   Araguaia
24163  150840    XINGUARA    9464     11893  2013   Araguaia
24173  150840    XINGUARA    8382     10459  2012   Araguaia

[2015 rows x 6 columns]

In [18]:
df.to_csv('dados_prontos/sexo_cadunico_tratado.csv',index=False)

In [19]:
#Pessoas inscritas no Cadastro Único - por raça/cor

df = pd.read_csv('dados_brutos/etnia_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
                   'Quantidade de pessoas brancas inscritas no Cadastro Único':'Brancos',
                   'Quantidade de pessoas pretas inscritas no Cadastro Único':'Pretos',
                   'Quantidade de pessoas amarelas inscritas no Cadastro Único':'Amarelos',
                   'Quantidade de pessoas pardas inscritas no Cadastro Único':'Pardos',
                   'Quantidade de pessoas indígenas inscritas no Cadastro Único':'Indigenas',
                   'Quantidade de pessoas sem informação sobre raça/cor inscritas no Cadastro Único':'NoData'},inplace=True)

df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df.drop(columns=['UF'],inplace=True)

df

,Codigo,Municipio,Brancos,Pretos,Amarelos,Pardos,Indigenas,NoData,Ano,RI
10,150010,ABAETETUBA,17050,7130,329,104856,67,2,2025,Tocantins
28,150010,ABAETETUBA,16892,6569,341,105911,71,2,2024,Tocantins
40,150010,ABAETETUBA,17864,6969,374,111004,68,5,2023,Tocantins
50,150010,ABAETETUBA,17519,6910,355,107976,71,7,2022,Tocantins
58,150010,ABAETETUBA,15476,6137,292,97017,71,5,2021,Tocantins
...,...,...,...,...,...,...,...,...,...,...
24127,150840,XINGUARA,2560,1027,60,18228,31,60,2016,Araguaia
24141,150840,XINGUARA,2665,1060,63,17126,27,70,2015,Araguaia
24151,150840,XINGUARA,3428,1409,69,18430,38,144,2014,Araguaia
24163,150840,XINGUARA,3283,1389,62,16292,41,290,2013,Araguaia
24173,150840,XINGUARA,3055,1493,50,14119,54,70,2012,Araguaia

In [20]:

df.to_csv('dados_prontos/etnia_cadunico_tratado.csv',index=False)

In [21]:
#Pessoas cadastradas no Cadastro Único - por faixa etária 

df = pd.read_csv('dados_brutos/faixa_etaria_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
                   'Número de pessoas com idade entre 0 e 3 anos cadastradas no Cadastro Único':'0-3',
                   'Número de pessoas com idade entre 4 e 6 anos cadastradas no Cadastro Único':'4-6',
                   'Número de pessoas com idade entre 7 e 15 anos cadastradas no Cadastro Único':'7-15',
                   'Número de pessoas com idade entre 16 e 17 anos cadastradas no Cadastro Único':'16-17',
                   'Número de pessoas com idade entre 18 e 24 anos cadastradas no Cadastro Único':'18-24',
                   'Número de pessoas com idade entre 25 e 34 anos cadastradas no Cadastro Único':'25-34',
                   'Número de pessoas com idade entre 35 e 39 anos cadastradas no Cadastro Único':'35-39',
                   'Número de pessoas com idade entre 40 e 44 anos cadastradas no Cadastro Único':'40-44',
                   'Número de pessoas com idade entre 45 e 49 anos cadastradas no Cadastro Único':'45-49',
                   'Número de pessoas com idade entre 50 e 54 anos cadastradas no Cadastro Único':'50-54',
                   'Número de pessoas com idade entre 55 e 59 anos cadastradas no Cadastro Único':'55-59',
                   'Número de pessoas com idade entre 60 e 64 anos cadastradas no Cadastro Único':'60-64',
                   'Número de pessoas com idade acima de 64 anos cadastradas no Cadastro Único':'64+',
                   'Número total de pessoas cadastradas no Cadastro Único':'Total'},inplace=True)


df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df.drop(columns=['UF'])

df

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
10,150010,ABAETETUBA,8254.0,7697.0,22248,5247,16582,22131,9572,8915,7558,6220,5091,3649,6270,129434,2025,Tocantins
28,150010,ABAETETUBA,8811.0,7590.0,22345,5278,17128,22589,9463,8661,7436,6144,4778,3536,6027,129786,2024,Tocantins
40,150010,ABAETETUBA,9132.0,7814.0,22644,5191,18826,24932,10175,9069,7574,6264,4912,3639,6112,136284,2023,Tocantins
50,150010,ABAETETUBA,8707.0,7680.0,22673,5148,19082,24229,9988,8686,7260,5893,4607,3265,5620,132838,2022,Tocantins
58,150010,ABAETETUBA,7825.0,7451.0,21982,4968,18135,20869,8607,7291,6085,4791,3697,2628,4669,118998,2021,Tocantins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24127,150840,XINGUARA,1679.0,1539.0,5241,1069,2669,3140,1459,1123,880,748,603,642,1188,21980,2016,Araguaia
24141,150840,XINGUARA,1529.0,1520.0,5135,1042,2562,3056,1374,1066,868,660,575,563,1061,21011,2015,Araguaia
24151,150840,XINGUARA,NaN,NaN,5467,1212,3163,3386,1461,1232,984,748,584,535,1642,20414,2014,Araguaia
24163,150840,XINGUARA,NaN,NaN,5257,1104,2901,2972,1309,1073,875,629,490,401,1461,18472,2013,Araguaia
24173,150840,XINGUARA,NaN,NaN,4969,1049,2546,2538,1205,953,743,503,363,373,1332,16574,2012,Araguaia

In [22]:
df.to_csv('dados_prontos/faixa_etaria_cadunico_tratado.csv',index=False)

In [23]:
df = pd.read_csv('dados_brutos/urbano_rural_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
'Número de pessoas cadastradas no Cadastro Único em domicílios rurais':'Rural',
'Número de pessoas cadastradas no Cadastro Único em domicílios urbanos':'Urbano'},inplace=True)

df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df.drop(columns=['UF'])

df

       Codigo   Municipio  Rural  Urbano   Ano         RI
10     150010  ABAETETUBA  63946   65461  2025  Tocantins
28     150010  ABAETETUBA  63386   66386  2024  Tocantins
40     150010  ABAETETUBA  65033   71237  2023  Tocantins
50     150010  ABAETETUBA  62679   70153  2022  Tocantins
58     150010  ABAETETUBA  56929   62065  2021  Tocantins
...       ...         ...    ...     ...   ...        ...
24127  150840    XINGUARA   2647   19319  2016   Araguaia
24141  150840    XINGUARA   2687   18324  2015   Araguaia
24151  150840    XINGUARA   2898   20620  2014   Araguaia
24163  150840    XINGUARA   2110   19247  2013   Araguaia
24173  150840    XINGUARA   2135   16706  2012   Araguaia

[2015 rows x 6 columns]

In [ ]:
df.to_csv('dados_prontos/urbano_rural_cadunico_tratado.csv',index=False)