In [26]:
from pathlib import Path

print(Path.cwd())

/home/fabricio_nascimento/Área de trabalho/dev/Artigo/ibge

In [27]:
import pandas as pd

dfEtnia2010 = pd.read_csv('censo2010/dados_tratados/etnia_ibge_2010_tratado.csv')
dfEtnia2010

,Codigo,Municipio,Branca,Preta,Amarela,Parda,Indígena,Total,RI,Ano
0,150010,Abaetetuba (PA),30676,9038,797,100509,80,141100,Tocantins,2010
1,150013,Abel Figueiredo (PA),1655,699,88,4327,11,6780,Rio Capim,2010
2,150020,Acará (PA),5985,4081,556,42900,47,53569,Tocantins,2010
3,150030,Afuá (PA),6826,1135,138,26942,1,35042,Marajó,2010
4,150034,Água Azul do Norte (PA),6788,1935,844,15486,4,25057,Araguaia,2010
...,...,...,...,...,...,...,...,...,...,...
138,150815,Uruará (PA),11896,3325,459,29071,38,44789,Xingu,2010
139,150820,Vigia (PA),11119,1877,229,34645,19,47889,Guamá,2010
140,150830,Viseu (PA),8954,3131,602,43983,46,56716,Rio Caeté,2010
141,150835,Vitória do Xingu (PA),3016,1061,306,8919,129,13431,Xingu,2010
142,150840,Xinguara (PA),10924,3062,801,25737,49,40573,Araguaia,2010

In [28]:
dfEtnia2022 = pd.read_csv('censo2022/dados_tratados/etnia_ibge_2022_tratado.csv')

dfEtnia2022

,Codigo,Municipio,Branca,Preta,Amarela,Parda,Indígena,Total,RI,Ano
0,1,Pará,1570281,793621,12432,5673446,69180,8120131,NaN,2022
1,150010,Abaetetuba (PA),29624,15895,107,112187,83,158188,Tocantins,2022
2,150013,Abel Figueiredo (PA),1228,640,-,4258,10,6136,Rio Capim,2022
3,150020,Acará (PA),5684,8503,65,44748,23,59023,Tocantins,2022
4,150030,Afuá (PA),5470,2567,24,29690,12,37765,Marajó,2022
...,...,...,...,...,...,...,...,...,...,...
140,150815,Uruará (PA),9503,4409,11,29535,100,43558,Xingu,2022
141,150820,Vigia (PA),10924,3632,24,36224,25,50832,Guamá,2022
142,150830,Viseu (PA),6782,3385,24,48435,66,58692,Rio Caeté,2022
143,150835,Vitória do Xingu (PA),2730,1666,24,10667,517,15607,Xingu,2022
144,150840,Xinguara (PA),12369,4933,69,35466,56,52893,Araguaia,2022

In [29]:
dfEtniaJunto = pd.concat([dfEtnia2010,dfEtnia2022])

dfEtniaJunto.to_csv('panorama1020/etnia_ibge.csv',index=False)

In [30]:
dfIdade2010 = pd.read_csv('censo2010/dados_tratados/faixa_etaria_ibge_2010_tratado.csv')
dfIdade2010

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano
0,15,Pará,584197,459462,1477017,318551,1051358,1324739,514535,434824,353997,294209,233028,174438,359797,7581051,2010
1,150010,Abaetetuba (PA),10342,8118,28235,6820,21305,24356,9333,7487,5943,4910,4155,3169,6889,141100,2010
2,150013,Abel Figueiredo (PA),532,413,1328,277,885,1191,431,388,341,249,212,173,359,6780,2010
3,150020,Acará (PA),4935,3856,11952,2438,7489,8101,3351,2692,2102,1588,1374,1145,2539,53569,2010
4,150030,Afuá (PA),3657,2889,8897,1740,4752,4992,1837,1480,1172,946,815,530,1329,35042,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,150815,Uruará (PA),3853,2899,8995,1884,6200,8331,2855,2409,1916,1601,1218,969,1653,44789,2010
140,150820,Vigia (PA),3409,2791,9043,2125,6763,8273,3123,2623,2116,1863,1640,1261,2849,47889,2010
141,150830,Viseu (PA),5682,4473,13338,2627,7546,8238,2975,2453,2099,1815,1585,1172,2711,56716,2010
142,150835,Vitória do Xingu (PA),942,809,2676,546,2080,2472,855,757,552,470,390,306,574,13431,2010
143,150840,Xinguara (PA),2984,2350,7665,1601,5555,7415,2913,2509,2097,1596,1283,903,1699,40573,2010

In [31]:
dfIdade2022 = pd.read_csv('censo2022/dados_tratados/faixa_etaria_ibge_2022_tratado.csv')
dfIdade2022

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano
0,15,Pará,538275,421518,1298790,292959,994826,1306506,650689,604614,490203,419361,346819,235151,641181,8120131,2022
1,150010,Abaetetuba (PA),10459,8071,24556,5591,20296,27807,12928,11467,9435,7836,6170,4075,11912,158188,2022
2,150013,Abel Figueiredo (PA),425,373,1001,202,667,864,473,477,343,356,298,204,568,6136,2022
3,150020,Acará (PA),4278,3372,10659,2510,7275,9183,4384,3956,3172,2863,2317,1489,4523,59023,2022
4,150030,Afuá (PA),3512,2693,7775,1630,5170,5879,2453,2189,1797,1414,1148,771,2075,37765,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,150815,Uruará (PA),3343,2474,7447,1591,5224,7030,3474,3136,2491,2093,1855,1164,3009,43558,2022
141,150820,Vigia (PA),2944,2382,7517,1793,5651,8222,4232,3963,3179,2796,2258,1591,4899,50832,2022
142,150830,Viseu (PA),4342,3492,11827,2701,7406,8578,4239,3693,2899,2386,2140,1579,4345,58692,2022
143,150835,Vitória do Xingu (PA),1087,962,2856,608,1783,2510,1155,1130,871,755,638,388,1102,15607,2022
144,150840,Xinguara (PA),3713,2832,8213,1816,6658,9024,4397,3954,3217,2646,2176,1370,3722,52893,2022

In [32]:
dfIdadeJunto = pd.concat([dfIdade2010,dfIdade2022])

dfIdadeJunto

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano
0,15,Pará,584197,459462,1477017,318551,1051358,1324739,514535,434824,353997,294209,233028,174438,359797,7581051,2010
1,150010,Abaetetuba (PA),10342,8118,28235,6820,21305,24356,9333,7487,5943,4910,4155,3169,6889,141100,2010
2,150013,Abel Figueiredo (PA),532,413,1328,277,885,1191,431,388,341,249,212,173,359,6780,2010
3,150020,Acará (PA),4935,3856,11952,2438,7489,8101,3351,2692,2102,1588,1374,1145,2539,53569,2010
4,150030,Afuá (PA),3657,2889,8897,1740,4752,4992,1837,1480,1172,946,815,530,1329,35042,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,150815,Uruará (PA),3343,2474,7447,1591,5224,7030,3474,3136,2491,2093,1855,1164,3009,43558,2022
141,150820,Vigia (PA),2944,2382,7517,1793,5651,8222,4232,3963,3179,2796,2258,1591,4899,50832,2022
142,150830,Viseu (PA),4342,3492,11827,2701,7406,8578,4239,3693,2899,2386,2140,1579,4345,58692,2022
143,150835,Vitória do Xingu (PA),1087,962,2856,608,1783,2510,1155,1130,871,755,638,388,1102,15607,2022
144,150840,Xinguara (PA),3713,2832,8213,1816,6658,9024,4397,3954,3217,2646,2176,1370,3722,52893,2022

In [33]:
dfIdadeJunto.to_csv('panorama1020/faixa_etaria_ibge.csv',index=False)

In [34]:
dfSexo2010 = pd.read_csv('censo2010/dados_tratados/sexo_ibge_2010_tratado.csv')
dfSexo2010

,Codigo,Municipio,Homens,Mulheres,Total,RI,Ano
0,1,Pará,3821837,3759214,7581051,NaN,2010
1,150010,Abaetetuba (PA),71630,69470,141100,Tocantins,2010
2,150013,Abel Figueiredo (PA),3533,3247,6780,Rio Capim,2010
3,150020,Acará (PA),28115,25454,53569,Tocantins,2010
4,150030,Afuá (PA),18453,16589,35042,Marajó,2010
...,...,...,...,...,...,...,...
139,150815,Uruará (PA),23633,21156,44789,Xingu,2010
140,150820,Vigia (PA),24548,23341,47889,Guamá,2010
141,150830,Viseu (PA),29817,26899,56716,Rio Caeté,2010
142,150835,Vitória do Xingu (PA),7281,6150,13431,Xingu,2010
143,150840,Xinguara (PA),20572,20001,40573,Araguaia,2010

In [35]:
dfSexo2022 = pd.read_csv('censo2022/dados_tratados/sexo_ibge_2022_tratado.csv')
dfSexo2022

,Codigo,Municipio,Homens,Mulheres,Total,RI,Ano
0,0,Brasil,98532431,104548325,203080756,NaN,2022
1,1,Pará,4051813,4068318,8120131,NaN,2022
2,150010,Abaetetuba (PA),79297,78891,158188,Tocantins,2022
3,150013,Abel Figueiredo (PA),3113,3023,6136,Rio Capim,2022
4,150020,Acará (PA),30551,28472,59023,Tocantins,2022
...,...,...,...,...,...,...,...
141,150815,Uruará (PA),22812,20746,43558,Xingu,2022
142,150820,Vigia (PA),25695,25137,50832,Guamá,2022
143,150830,Viseu (PA),30472,28220,58692,Rio Caeté,2022
144,150835,Vitória do Xingu (PA),8031,7576,15607,Xingu,2022
145,150840,Xinguara (PA),26590,26303,52893,Araguaia,2022

In [36]:
dfSexoJunto = pd.concat([dfSexo2022,dfSexo2010])

dfSexoJunto.to_csv('panorama1020/sexo_ibge.csv',index=False)

In [37]:
dfUrbe2010 = pd.read_csv('censo2010/dados_tratados/urbano_rural_ibge_2010_tratado.csv')
dfUrbe2010

     Codigo                Município  Urbana  Rural   Total         RI   Ano
0    150010          Abaetetuba (PA)   82998  58102  141100  Tocantins  2010
1    150013     Abel Figueiredo (PA)    6034    746    6780  Rio Capim  2010
2    150020               Acará (PA)   12621  40948   53569  Tocantins  2010
3    150030                Afuá (PA)    9478  25564   35042     Marajó  2010
4    150034  Água Azul do Norte (PA)    4876  20181   25057   Araguaia  2010
..      ...                      ...     ...    ...     ...        ...   ...
138  150815              Uruará (PA)   24430  20359   44789      Xingu  2010
139  150820               Vigia (PA)   32353  15536   47889      Guamá  2010
140  150830               Viseu (PA)   18397  38319   56716  Rio Caeté  2010
141  150835    Vitória do Xingu (PA)    5362   8069   13431      Xingu  2010
142  150840            Xinguara (PA)   31492   9081   40573   Araguaia  2010

[143 rows x 7 columns]

In [38]:
dfUrbe2022 = pd.read_csv('censo2022/dados_tratados/urbano_rural_ibge_2022_tratado.csv')
dfUrbe2022

,Codigo,Municipio,Urbana,Rural,Total,RI,Ano
0,0,Brasil,177508417,25572339,203080756,NaN,2022
1,1,Pará,6095530,2024601,8120131,NaN,2022
2,150010,Abaetetuba (PA),98390,59798,158188,Tocantins,2022
3,150013,Abel Figueiredo (PA),5366,770,6136,Rio Capim,2022
4,150020,Acará (PA),13079,45944,59023,Tocantins,2022
...,...,...,...,...,...,...,...
141,150815,Uruará (PA),25678,17880,43558,Xingu,2022
142,150820,Vigia (PA),39596,11236,50832,Guamá,2022
143,150830,Viseu (PA),29936,28756,58692,Rio Caeté,2022
144,150835,Vitória do Xingu (PA),8700,6907,15607,Xingu,2022
145,150840,Xinguara (PA),46390,6503,52893,Araguaia,2022

In [39]:
dfUrbeJunto = pd.concat([dfUrbe2010,dfUrbe2022])

dfUrbeJunto.to_csv('panorama1020/urbano_rural_ibge.csv',index=False)