In [8]:
import pandas as pd
from helper import codigo_to_ri


dfIdade2010 = pd.read_csv('censo2010/dados_tratados/faixa_etaria_ibge_2010_tratado.csv')

dfIdade2010['Ano'] = 2010

dfIdade2010

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano
0,15,Pará,584197,459462,1477017,318551,1051358,1324739,514535,434824,353997,294209,233028,174438,359797,7581051,2010
1,150010,Abaetetuba (PA),10342,8118,28235,6820,21305,24356,9333,7487,5943,4910,4155,3169,6889,141100,2010
2,150013,Abel Figueiredo (PA),532,413,1328,277,885,1191,431,388,341,249,212,173,359,6780,2010
3,150020,Acará (PA),4935,3856,11952,2438,7489,8101,3351,2692,2102,1588,1374,1145,2539,53569,2010
4,150030,Afuá (PA),3657,2889,8897,1740,4752,4992,1837,1480,1172,946,815,530,1329,35042,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,150815,Uruará (PA),3853,2899,8995,1884,6200,8331,2855,2409,1916,1601,1218,969,1653,44789,2010
140,150820,Vigia (PA),3409,2791,9043,2125,6763,8273,3123,2623,2116,1863,1640,1261,2849,47889,2010
141,150830,Viseu (PA),5682,4473,13338,2627,7546,8238,2975,2453,2099,1815,1585,1172,2711,56716,2010
142,150835,Vitória do Xingu (PA),942,809,2676,546,2080,2472,855,757,552,470,390,306,574,13431,2010
143,150840,Xinguara (PA),2984,2350,7665,1601,5555,7415,2913,2509,2097,1596,1283,903,1699,40573,2010

In [9]:
dfIdade2022 = pd.read_csv('censo2022/dados_tratados/faixa_etaria_ibge_2022_tratado.csv')

dfIdade2022['Ano'] = 2022

dfIdade2022

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano
0,15,Pará,538275,421518,1298790,292959,994826,1306506,650689,604614,490203,419361,346819,235151,641181,8120131,2022
1,150010,Abaetetuba (PA),10459,8071,24556,5591,20296,27807,12928,11467,9435,7836,6170,4075,11912,158188,2022
2,150013,Abel Figueiredo (PA),425,373,1001,202,667,864,473,477,343,356,298,204,568,6136,2022
3,150020,Acará (PA),4278,3372,10659,2510,7275,9183,4384,3956,3172,2863,2317,1489,4523,59023,2022
4,150030,Afuá (PA),3512,2693,7775,1630,5170,5879,2453,2189,1797,1414,1148,771,2075,37765,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,150815,Uruará (PA),3343,2474,7447,1591,5224,7030,3474,3136,2491,2093,1855,1164,3009,43558,2022
141,150820,Vigia (PA),2944,2382,7517,1793,5651,8222,4232,3963,3179,2796,2258,1591,4899,50832,2022
142,150830,Viseu (PA),4342,3492,11827,2701,7406,8578,4239,3693,2899,2386,2140,1579,4345,58692,2022
143,150835,Vitória do Xingu (PA),1087,962,2856,608,1783,2510,1155,1130,871,755,638,388,1102,15607,2022
144,150840,Xinguara (PA),3713,2832,8213,1816,6658,9024,4397,3954,3217,2646,2176,1370,3722,52893,2022

In [10]:
dfIdadeIBGE = pd.concat([dfIdade2010,dfIdade2022])

dfIdadeIBGE = codigo_to_ri(dfIdadeIBGE)

dfIdadeIBGE

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
0,000015,Pará,584197,459462,1477017,318551,1051358,1324739,514535,434824,353997,294209,233028,174438,359797,7581051,2010,NaN
1,150010,Abaetetuba (PA),10342,8118,28235,6820,21305,24356,9333,7487,5943,4910,4155,3169,6889,141100,2010,Tocantins
2,150013,Abel Figueiredo (PA),532,413,1328,277,885,1191,431,388,341,249,212,173,359,6780,2010,Rio Capim
3,150020,Acará (PA),4935,3856,11952,2438,7489,8101,3351,2692,2102,1588,1374,1145,2539,53569,2010,Tocantins
4,150030,Afuá (PA),3657,2889,8897,1740,4752,4992,1837,1480,1172,946,815,530,1329,35042,2010,Marajó
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,150815,Uruará (PA),3343,2474,7447,1591,5224,7030,3474,3136,2491,2093,1855,1164,3009,43558,2022,Xingu
141,150820,Vigia (PA),2944,2382,7517,1793,5651,8222,4232,3963,3179,2796,2258,1591,4899,50832,2022,Guamá
142,150830,Viseu (PA),4342,3492,11827,2701,7406,8578,4239,3693,2899,2386,2140,1579,4345,58692,2022,Rio Caeté
143,150835,Vitória do Xingu (PA),1087,962,2856,608,1783,2510,1155,1130,871,755,638,388,1102,15607,2022,Xingu
144,150840,Xinguara (PA),3713,2832,8213,1816,6658,9024,4397,3954,3217,2646,2176,1370,3722,52893,2022,Araguaia

In [11]:
dfIdadeIBGE.to_csv('dados_prontos/faixa_etaria_ibge.csv',index=False)